name: normits_lu
channels:
  - conda-forge
dependencies:
  - openpyxl=3.1.2
  - pip=24.0
  - python=3.11.8
  - pandas>2
  - numpy<2
  - pyyaml=6.0.1
  - seaborn=0.13.2
  - matplotlib=3.9.1
  - pip:
      - git+https://github.com/asongtoruin/caf.core@iteration_5_testing
      - git+https://github.com/Transport-for-the-North/caf.space
