name: normits_lu
channels:
  - conda-forge
dependencies:
  - caf.toolkit>=0.0.7
  - pandas>=1.4.0, <2
  - psycopg2>=2
  - pydantic>=1
  - python=3.10
  - geopandas>=0.8
  - pyodbc=5.0.1=py310h00ffb61_0
  - fsspec=2023.12.1=pyhca7485f_0
