# Configuration file specifying the segmentation and geographical level of the input data.
# All files here are assumed to be in a format ready for DVectors.
input_root_directory: I:\NorMITs Land Use\2023\import
output_directory: F:\Working\Land-Use\OUTPUTS_validation testing revamp 2
output_intermediate_outputs: False
scotland_donor_regions: [NE, NW, YH]

base_data:
    unoccupied_households:
        file_path: RM002 accom type by household size\preprocessing\2072764328175065 zero.hdf
        geographical_level: LSOA2021
        input_segments: [accom_h]
        # IDEALLY we might also have a "desired_segments" here, in case the input data is at an unrequired level of detail

    occupied_households:
        file_path: RM002 accom type by household size\preprocessing\2672385425907310 all.hdf
        geographical_level: LSOA2021
        input_segments: [accom_h]

    ons_table_1:
        file_path: ONS custom\preprocessing\ct210212census2021.hdf
        geographical_level: LSOA2021
        input_segments: [accom_h]

    addressbase_dwellings:
        file_path: ABP\ABP2021\preprocessing\output_results_all_2021(no red).hdf
        geographical_level: LSOA2021
        input_segments: [accom_h]

    ons_table_2:
        file_path: ONS custom\preprocessing\ct210213census2021.hdf
        geographical_level: MSOA2021
        input_segments: [accom_h, adults, children, car_availability]

    ons_table_4:
        file_path: ONS custom\preprocessing\ct210215census2021.hdf
        geographical_level: LSOA2021
        input_segments: [accom_h, ns_sec]

    hh_age_gender_2021:
        file_path: ONS\preprocessing\population_hh_age11_gender_MSOA.hdf
        geographical_level: MSOA2021
        input_segments: [accom_h, age_9, g]

    ons_table_3:
        file_path: ONS custom\preprocessing\ct210214census2021_-8_modified.hdf
        geographical_level: MSOA2021
        input_segments: [accom_h, ns_sec, economic_status, pop_emp, soc]

    ce_uplift_factor:
        file_path: TS001 pop_hh_ce\preprocessing\1226171533660024.hdf
        geographical_level: LSOA2021
        input_segments: [total]

    ce_pop_by_type:
        file_path: TS048  CERs by type\preprocessing\2741727163807526.hdf
        geographical_level: MSOA2021
        input_segments: [ce]

    ce_pop_by_age_gender_soc:
        file_path: ONS\ONS 2021 CERs\preprocessing\CERs_GOR_age11_gender_occupation.hdf
        geographical_level: RGN2021
        input_segments: [age_9, g, soc]

    ce_pop_by_age_gender_econ:
        file_path: ONS\ONS 2021 CERs\preprocessing\CERs_GOR_age11_gender_economicstatus_-8_modified.hdf
        geographical_level: RGN2021
        input_segments: [age_9, g, economic_status]

    scotland_population:
        file_path: Census Scotland\preprocessing\Population_age6_gender_DZ2011.hdf
        geographical_level: DZ2011
        input_segments: [g, scot_age]

household_validation_data:
    car_availability:
        file_path: ONS-validation\preprocessing\households_cars_lsoa_3.hdf
        geographical_level: LSOA2021
        input_segments: [car_availability]
    adults_children:
        file_path: ONS-validation\preprocessing\households_adults_children_lsoa_adults-children-aggregated.hdf
        geographical_level: LSOA2021
        input_segments: [adults, children]
    adults_children_nssec:
        file_path: ONS-validation\preprocessing\households_nssec_adults_children_lad_adults-children-nssec-aggregated.hdf
        geographical_level: LAD2021
        input_segments: [adults, children, ns_sec]
    car_availability_nssec:
        file_path: ONS-validation\preprocessing\households_nssec_car_lad_nssec-aggregated.hdf
        geographical_level: LAD2021
        input_segments: [car_availability, ns_sec]
    nssec:
        file_path: ONS-validation\preprocessing\households_nssec_lsoa.hdf
        geographical_level: LSOA2021
        input_segments: [ns_sec]

population_adjustment_data:
    validation_data:
        - file_path: ONS-validation\preprocessing\population_soc9_lsoa_soc-aggregated.hdf
          geographical_level: LSOA2021
          input_segments: [soc]
        - file_path: ONS-validation\preprocessing\population_status_lsoa.hdf
          geographical_level: LSOA2021
          input_segments: [economic_status]
        - file_path: ONS-validation\preprocessing\population_age11_gender_occupation_lad_age-occ-aggregated.hdf
          geographical_level: LAD2021
          input_segments: [age_9, g, soc]
        - file_path: ONS-validation\preprocessing\population_age11_gender_economicstatus_region_age-econ-aggregated.hdf
          geographical_level: RGN2021
          input_segments: [age_9, g, economic_status]
        - file_path: ONS-validation\preprocessing\population_age11_gender_MSOA_age-aggregated.hdf
          geographical_level: MSOA2021
          input_segments: [age_9, g]
        - file_path: ONS-validation\preprocessing\population_adults_children_status_region_adults-children-aggregated.hdf
          geographical_level: RGN2021
          input_segments: [adults, children, economic_status]
        - file_path: ONS-validation\preprocessing\population_adults_children_occupation_lad_adults-children-soc-aggregated.hdf
          geographical_level: LAD2021
          input_segments: [adults, children, soc]
        - file_path: ONS-validation\preprocessing\population_adults_children_age_gender_MSOA_adults-children-age-aggregated.hdf
          geographical_level: MSOA2021
          input_segments: [adults, children, age_9, g]
        - file_path: ONS-validation\preprocessing\population_age_gender_car_msoa_age-aggregated.hdf
          geographical_level: MSOA2021
          input_segments: [car_availability, age_9, g]

    rebase_data:
        - file_path: MYPE\preprocessing\sapelsoasyoatablefinal.hdf
          geographical_level: LSOA2021
          input_segments: [g, age_9]
