# Configuration file specifying the segmentation and geographical level of the input data.
# All files here are assumed to be in a format ready for DVectors.
input_root_directory: I:\NorMITs Land Use\2023\import
output_directory: F:\Working\Land-Use\OUTPUTS\AR_EMP_CHECK
output_intermediate_outputs: False

# Currently bres data only includes England and Wales

base_data:
    lad_4_digit_sic:
        file_path: BRES2022\Employment\preprocessing\bres_employment22_lad_4digit_sic.hdf
        geographical_level: LAD2021
        input_segments: [sic_4_digit]

    msoa_2011_2_digit_sic:
        file_path: BRES2022\Employment\preprocessing\bres_employment22_msoa2011_2digit_sic_jobs.hdf
        geographical_level: MSOA2011
        input_segments: [sic_2_digit]

    msoa_2011_2_digit_sic_1_digit_sic_splits:
        file_path: BRES2022\Employment\preprocessing\bres_employment22_msoa2011_2digit_sic_1digit_sic_splits.hdf
        geographical_level: MSOA2011
        input_segments: [sic_1_digit, sic_2_digit]

    lsoa_2011_1_digit_sic:
        file_path: BRES2022\Employment\preprocessing\bres_employment22_lsoa2011_1digit_sic.hdf
        geographical_level: LSOA2011
        input_segments: [sic_1_digit]

    ons_sic_soc_jobs_lu:
        file_path: ONS\industry_occupation\preprocessing\population_region_1sic_soc.hdf
        geographical_level: RGN2021
        input_segments: [sic_1_digit, soc]

    wfj:
        file_path: BRES2022\Employment\Employment Investigation\preprocessing\WFJ.hdf
        geographical_level: RGN2021
        input_segments: [total]

    soc_4_factors:
        file_path: SOC\preprocessing\Table 8 WFJ-adjusted Land Use SOC4.hdf
        geographical_level: RGN2021
        input_segments: [total]
