# Configuration file specifying the segmentation and geographical level of the input data.
# All files here are assumed to be in a format ready for DVectors.
input_root_directory: I:\NorMITs Land Use\2023\import
output_directory: OUTPUTS

occupied_households:
    file_path: RM002 accom type by household size\preprocessing\2072764328175065 zero.hdf
    geographical_level: LSOA2021
    input_segments: [h]
    # IDEALLY we might also have a "desired_segments" here, in case the input data is at an unrequired level of detail

unoccupied_households:
    file_path: RM002 accom type by household size\preprocessing\2672385425907310 all.hdf
    geographical_level: LSOA2021
    input_segments: [h]

ons_table_1:
    file_path: ONS custom\preprocessing\ct210212census2021.hdf
    geographical_level: LSOA2021
    input_segments: [h]

addressbase_dwellings:
    file_path: ABP\ABP2021\preprocessing\output_results_all_2021(no red).hdf
    geographical_level: LSOA2021
    input_segments: [h]

ons_table_2:
    file_path: ONS custom\preprocessing\ct210213census2021.hdf
    geographical_level: MSOA2021
    input_segments: [h, ha, hc, car]

mype_2022:
    file_path: MYPE\preprocessing\sapelsoasyoatablefinal.hdf
    geographical_level: LSOA2021
    input_segments: [gender, age]

ons_table_4:
    file_path: ONS custom\preprocessing\ct210215census2021.hdf
    geographical_level: LSOA2021
    input_segments: [h, ns_sec]

hh_age_gender_2021:
    file_path: ONS\population_hh_age5_gender_MSOA\preprocessing\MSOA_age5_gender_hh_EnglandWales.hdf
    geographical_level: MSOA2021
    input_segments: [h, agg_age, gender]

ons_table_3:
    file_path: ONS custom\preprocessing\ct210214census2021.hdf
    geographical_level: MSOA2021
    input_segments: [h, ns_sec, pop_soc]