from typing import Dict, List

from caf.core.segments import SegmentsSuper, Segment, Exclusion


def is_standard_segment(identifier: str) -> bool:
    """Confirm whether a provided string corresponds to a standard Segment

    Parameters
    ----------
    identifier : str
        String to check

    Returns
    -------
    bool
        True if belonging to a standard segment, else False.
    """
    try:
        SegmentsSuper(identifier)
        return True
    except ValueError:
        return False


def split_input_segments(input_segments: List[str]) -> Dict[bool, List[str]]:
    """Splits a list of input segment strings into standard segments and custom

    Parameters
    ----------
    input_segments : List[str]
        Segment strings to check

    Returns
    -------
    Dict[bool, List[str]]
        Dictionary with two keys - True and False - with a list for each. True
        corresponds to those segments which are "standard", False corresponds
        to those which are likely to be custom.
    """
    # Could do this with a defaultdict but it's simple enough to not care, and
    # this way we *definitely* get both keys every time
    output_dict : dict[bool, list] = {
        True: [], False: []
    }

    # Update respective lists
    for seg_str in input_segments:
        output_dict[is_standard_segment(seg_str)].append(seg_str)

    return output_dict


_CUSTOM_SEGMENT_CATEGORIES = {
    "total": {
        1: "all"
    },
    "h": {
        1: "Whole house or bungalow: Detached",
        2: "Whole house or bungalow: Semi-detached",
        3: "Whole house or bungalow: Terraced",
        4: "Flat, maisonette or apartment",
        5: "A caravan or other mobile or temporary structure",
    },
    "hr": {
        1: "Whole house or bungalow: Detached",
        2: "Whole house or bungalow: Semi-detached",
        3: "Whole house or bungalow: Terraced",
        4: "Flat, maisonette or apartment",
    },
    "ha": {
        1: "No adults or 1 adult in household",
        2: "2 adults in household",
        3: "3 or more adults in household",
    },
    "hc": {
        1: "Household with no children or all children non-dependent",
        2: "Household with one or more dependent children",
    },
    "car": {
        1: "No cars or vans in household",
        2: "1 car or van in household",
        3: "2 or more cars or vans in household",
    },
    "age": {
        1: "0 to 4 years",
        2: "5 to 9 years",
        3: "10 to 15 years",
        4: "16 to 19 years",
        5: "20 to 34 years",
        6: "35 to 49 years",
        7: "50 to 64 years",
        8: "65 to 74 years",
        9: "75+ years",
    },
    "agg_age": {
        1: "aged 15 years and under",
        2: "aged 16 to 24 years",
        3: "aged 25 to 34 years",
        4: "aged 35 to 49 years",
        5: "aged 50 years and over"
    },
    "scot_age": {
        1: "0 - 15",
        2: "16 - 24",
        3: "25 - 34",
        4: "35 - 49",
        5: "50 - 64",
        6: "65 and over"
    },
    "gender": {
        1: "male",
        2: "female"
    },
    "ns_sec": {
        1: "HRP managerial / professional",
        2: "HRP intermediate / technical",
        3: "HRP semi-routine / routine",
        4: "HRP never worked / long-term unemployed",
        5: "HRP full-time student"
    },
    "big": {
        1: "1 : Agriculture, forestry & fishing (A)",
        2: "2 : Mining, quarrying & utilities (B,D and E)",
        3: "3 : Manufacturing (C)",
        4: "4 : Construction (F)",
        5: "5 : Motor trades (Part G)",
        6: "6 : Wholesale (Part G)",
        7: "7 : Retail (Part G)",
        8: "8 : Transport & storage (inc postal) (H)",
        9: "9 : Accommodation & food services (I)",
        10: "10 : Information & communication (J)",
        11: "11 : Financial & insurance (K)",
        12: "12 : Property (L)",
        13: "13 : Professional, scientific & technical (M)",
        14: "14 : Business administration & support services (N)",
        15: "15 : Public administration & defence (O)",
        16: "16 : Education (P)",
        17: "17 : Health (Q)",
        18: "18 : Arts, entertainment, recreation & other services (R,S,T and U)",
    },
    "pop_soc": {
        1: "SOC1",
        2: "SOC2",
        3: "SOC3",
        4: "SOC4"
    },
    'pop_emp': {
        1: 'full_time',
        2: 'part_time',
        3: 'unemployed',
        4: 'students',
        5: 'non-working_age'
    },
    'pop_econ': {
        1: 'Economically active employees',
        2: 'Economically active unemployed',
        3: 'Economically inactive',
        4: 'Students'
    },
    'ce': {
        1: 'Medical and care',
        2: 'Defence',
        3: 'Prison, approved premises, and detention',
        4: 'Education',
        5: 'Hotels, hostels, holiday accommodation, and travel',
        6: 'Religion',
        7: 'Staff'
    },
    'sic_1_digit': {
        1: 'A : Agriculture, forestry and fishing',
        2: 'B : Mining and quarrying',
        3: 'C : Manufacturing',
        4: 'D : Electricity, gas, steam and air conditioning supply',
        5: 'E : Water supply; sewerage, waste management and remediation activities',
        6: 'F : Construction',
        7: 'G : Wholesale and retail trade; repair of motor vehicles and motorcycles',
        8: 'H : Transportation and storage',
        9: 'I : Accommodation and food service activities',
        10: 'J : Information and communication',
        11: 'K : Financial and insurance activities',
        12: 'L : Real estate activities',
        13: 'M : Professional, scientific and technical activities',
        14: 'N : Administrative and support service activities',
        15: 'O : Public administration and defence; compulsory social security',
        16: 'P : Education',
        17: 'Q : Human health and social work activities',
        18: 'R : Arts, entertainment and recreation',
        19: 'S : Other service activities',
        20: 'T : Activities of households as employers;undifferentiated goods-and services-producing activities of households for own use',
        21: 'U : Activities of extraterritorial organisations and bodies',
    },
    'sic_2_digit': {
        1: "01 : Crop and animal production, hunting and related service activities",
        2: "02 : Forestry and logging",
        3: "03 : Fishing and aquaculture",
        5: "05 : Mining of coal and lignite",
        6: "06 : Extraction of crude petroleum and natural gas",
        7: "07 : Mining of metal ores",
        8: "08 : Other mining and quarrying",
        9: "09 : Mining support service activities",
        10: "10 : Manufacture of food products",
        11: "11 : Manufacture of beverages",
        12: "12 : Manufacture of tobacco products",
        13: "13 : Manufacture of textiles",
        14: "14 : Manufacture of wearing apparel",
        15: "15 : Manufacture of leather and related products",
        16: "16 : Manufacture of wood and of products of wood and cork, except furniture;manufacture of articles of straw and plaiting materials",
        17: "17 : Manufacture of paper and paper products",
        18: "18 : Printing and reproduction of recorded media",
        19: "19 : Manufacture of coke and refined petroleum products",
        20: "20 : Manufacture of chemicals and chemical products",
        21: "21 : Manufacture of basic pharmaceutical products and pharmaceutical preparations",
        22: "22 : Manufacture of rubber and plastic products",
        23: "23 : Manufacture of other non-metallic mineral products",
        24: "24 : Manufacture of basic metals",
        25: "25 : Manufacture of fabricated metal products, except machinery and equipment",
        26: "26 : Manufacture of computer, electronic and optical products",
        27: "27 : Manufacture of electrical equipment",
        28: "28 : Manufacture of machinery and equipment n.e.c.",
        29: "29 : Manufacture of motor vehicles, trailers and semi-trailers",
        30: "30 : Manufacture of other transport equipment",
        31: "31 : Manufacture of furniture",
        32: "32 : Other manufacturing",
        33: "33 : Repair and installation of machinery and equipment",
        35: "35 : Electricity, gas, steam and air conditioning supply",
        36: "36 : Water collection, treatment and supply",
        37: "37 : Sewerage",
        38: "38 : Waste collection, treatment and disposal activities; materials recovery",
        39: "39 : Remediation activities and other waste management services. This division includes the provision of remediation services, i.e. the cleanup of contaminated buildings and sites, soil, surface or ground water.",
        41: "41 : Construction of buildings",
        42: "42 : Civil engineering",
        43: "43 : Specialised construction activities",
        45: "45 : Wholesale and retail trade and repair of motor vehicles and motorcycles",
        46: "46 : Wholesale trade, except of motor vehicles and motorcycles",
        47: "47 : Retail trade, except of motor vehicles and motorcycles",
        49: "49 : Land transport and transport via pipelines",
        50: "50 : Water transport",
        51: "51 : Air transport",
        52: "52 : Warehousing and support activities for transportation",
        53: "53 : Postal and courier activities",
        55: "55 : Accommodation",
        56: "56 : Food and beverage service activities",
        58: "58 : Publishing activities",
        59: "59 : Motion picture, video and television programme production, sound recording and music publishing activities",
        60: "60 : Programming and broadcasting activities",
        61: "61 : Telecommunications",
        62: "62 : Computer programming, consultancy and related activities",
        63: "63 : Information service activities",
        64: "64 : Financial service activities, except insurance and pension funding",
        65: "65 : Insurance, reinsurance and pension funding, except compulsory social security",
        66: "66 : Activities auxiliary to financial services and insurance activities",
        68: "68 : Real estate activities",
        69: "69 : Legal and accounting activities",
        70: "70 : Activities of head offices; management consultancy activities",
        71: "71 : Architectural and engineering activities; technical testing and analysis",
        72: "72 : Scientific research and development",
        73: "73 : Advertising and market research",
        74: "74 : Other professional, scientific and technical activities",
        75: "75 : Veterinary activities",
        77: "77 : Rental and leasing activities",
        78: "78 : Employment activities",
        79: "79 : Travel agency, tour operator and other reservation service and related activities",
        80: "80 : Security and investigation activities",
        81: "81 : Services to buildings and landscape activities",
        82: "82 : Office administrative, office support and other business support activities",
        84: "84 : Public administration and defence; compulsory social security",
        85: "85 : Education",
        86: "86 : Human health activities",
        87: "87 : Residential care activities",
        88: "88 : Social work activities without accommodation",
        90: "90 : Creative, arts and entertainment activities",
        91: "91 : Libraries, archives, museums and other cultural activities",
        92: "92 : Gambling and betting activities",
        93: "93 : Sports activities and amusement and recreation activities",
        94: "94 : Activities of membership organisations",
        95: "95 : Repair of computers and personal and household goods",
        96: "96 : Other personal service activities",
        97: "97 : Activities of households as employers of domestic personnel",
        98: "98 : Undifferentiated goods- and services-producing activities of private households for own use",
        99: "99 : Activities of extraterritorial organisations and bodies",
    },
    'sic_4_digit':
    {
        # Note that double quotes are required for some entries as the text includes apostrophes
        1: "0100 : DEFRA/Scottish Executive Agricultural Data",
        2: "0111 : Growing of cereals (except rice), leguminous crops and oil seeds",
        3: "0112 : Growing of rice",
        4: "0113 : Growing of vegetables and melons, roots and tubers",
        5: "0114 : Growing of sugar cane",
        6: "0115 : Growing of tobacco",
        7: "0116 : Growing of fibre crops",
        8: "0119 : Growing of other non-perennial crops",
        9: "0121 : Growing of grapes",
        10: "0122 : Growing of tropical and subtropical fruits",
        11: "0123 : Growing of citrus fruits",
        12: "0124 : Growing of pome fruits and stone fruits",
        13: "0125 : Growing of other tree and bush fruits and nuts",
        14: "0126 : Growing of oleaginous fruits",
        15: "0127 : Growing of beverage crops",
        16: "0128 : Growing of spices, aromatic, drug and pharmaceutical crops",
        17: "0129 : Growing of other perennial crops",
        18: "0130 : Plant propagation",
        19: "0141 : Raising of dairy cattle",
        20: "0142 : Raising of other cattle and buffaloes",
        21: "0143 : Raising of horses and other equines",
        22: "0144 : Raising of camels and camelids",
        23: "0145 : Raising of sheep and goats",
        24: "0146 : Raising of swine/pigs",
        25: "0147 : Raising of poultry",
        26: "0149 : Raising of other animals",
        27: "0150 : Mixed farming",
        28: "0161 : Support activities for crop production",
        29: "0162 : Support activities for animal production",
        30: "0163 : Post-harvest crop activities",
        31: "0164 : Seed processing for propagation",
        32: "0170 : Hunting, trapping and related service activities",
        33: "0210 : Silviculture and other forestry activities",
        34: "0220 : Logging",
        35: "0230 : Gathering of wild growing non-wood products",
        36: "0240 : Support services to forestry",
        37: "0311 : Marine fishing",
        38: "0312 : Freshwater fishing",
        39: "0321 : Marine aquaculture",
        40: "0322 : Freshwater aquaculture",
        41: "0510 : Mining of hard coal",
        42: "0520 : Mining of lignite",
        43: "0610 : Extraction of crude petroleum",
        44: "0620 : Extraction of natural gas",
        45: "0710 : Mining of iron ores",
        46: "0721 : Mining of uranium and thorium ores",
        47: "0729 : Mining of other non-ferrous metal ores",
        48: "0811 : Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate",
        49: "0812 : Operation of gravel and sand pits; mining of clays and kaolin",
        50: "0891 : Mining of chemical and fertiliser minerals",
        51: "0892 : Extraction of peat",
        52: "0893 : Extraction of salt",
        53: "0899 : Other mining and quarrying n.e.c.",
        54: "0910 : Support activities for petroleum and natural gas extraction",
        55: "0990 : Support activities for other mining and quarrying",
        56: "1011 : Processing and preserving of meat",
        57: "1012 : Processing and preserving of poultry meat",
        58: "1013 : Production of meat and poultry meat products",
        59: "1020 : Processing and preserving of fish, crustaceans and molluscs",
        60: "1031 : Processing and preserving of potatoes",
        61: "1032 : Manufacture of fruit and vegetable juice",
        62: "1039 : Other processing and preserving of fruit and vegetables",
        63: "1041 : Manufacture of oils and fats",
        64: "1042 : Manufacture of margarine and similar edible fats",
        65: "1051 : Operation of dairies and cheese making",
        66: "1052 : Manufacture of ice cream",
        67: "1061 : Manufacture of grain mill products",
        68: "1062 : Manufacture of starches and starch products",
        69: "1071 : Manufacture of bread; manufacture of fresh pastry goods and cakes",
        70: "1072 : Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes",
        71: "1073 : Manufacture of macaroni, noodles, couscous and similar farinaceous products",
        72: "1081 : Manufacture of sugar",
        73: "1082 : Manufacture of cocoa, chocolate and sugar confectionery",
        74: "1083 : Processing of tea and coffee",
        75: "1084 : Manufacture of condiments and seasonings",
        76: "1085 : Manufacture of prepared meals and dishes",
        77: "1086 : Manufacture of homogenised food preparations and dietetic food",
        78: "1089 : Manufacture of other food products n.e.c.",
        79: "1091 : Manufacture of prepared feeds for farm animals",
        80: "1092 : Manufacture of prepared pet foods",
        81: "1101 : Distilling, rectifying and blending of spirits",
        82: "1102 : Manufacture of wine from grape",
        83: "1103 : Manufacture of cider and other fruit wines",
        84: "1104 : Manufacture of other non-distilled fermented beverages",
        85: "1105 : Manufacture of beer",
        86: "1106 : Manufacture of malt",
        87: "1107 : Manufacture of soft drinks; production of mineral waters and other bottled waters",
        88: "1200 : Manufacture of tobacco products",
        89: "1310 : Preparation and spinning of textile fibres",
        90: "1320 : Weaving of textiles",
        91: "1330 : Finishing of textiles",
        92: "1391 : Manufacture of knitted and crocheted fabrics",
        93: "1392 : Manufacture of made-up textile articles, except apparel",
        94: "1393 : Manufacture of carpets and rugs",
        95: "1394 : Manufacture of cordage, rope, twine and netting",
        96: "1395 : Manufacture of non-wovens and articles made from non-wovens, except apparel",
        97: "1396 : Manufacture of other technical and industrial textiles",
        98: "1399 : Manufacture of other textiles n.e.c.",
        99: "1411 : Manufacture of leather clothes",
        100: "1412 : Manufacture of workwear",
        101: "1413 : Manufacture of other outerwear",
        102: "1414 : Manufacture of underwear",
        103: "1419 : Manufacture of other wearing apparel and accessories",
        104: "1420 : Manufacture of articles of fur",
        105: "1431 : Manufacture of knitted and crocheted hosiery",
        106: "1439 : Manufacture of other knitted and crocheted apparel",
        107: "1511 : Tanning and dressing of leather; dressing and dyeing of fur",
        108: "1512 : Manufacture of luggage, handbags and the like, saddlery and harness",
        109: "1520 : Manufacture of footwear",
        110: "1610 : Sawmilling and planing of wood",
        111: "1621 : Manufacture of veneer sheets and wood-based panels",
        112: "1622 : Manufacture of assembled parquet floors",
        113: "1623 : Manufacture of other builders' carpentry and joinery",
        114: "1624 : Manufacture of wooden containers",
        115: "1629 : Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting",
        116: "1711 : Manufacture of pulp",
        117: "1712 : Manufacture of paper and paperboard",
        118: "1721 : Manufacture of corrugated paper and paperboard and of containers of paper and paperboard",
        119: "1722 : Manufacture of household and sanitary goods and of toilet requisites",
        120: "1723 : Manufacture of paper stationery",
        121: "1724 : Manufacture of wallpaper",
        122: "1729 : Manufacture of other articles of paper and paperboard n.e.c.",
        123: "1811 : Printing of newspapers",
        124: "1812 : Other printing",
        125: "1813 : Pre-press and pre-media services",
        126: "1814 : Binding and related services",
        127: "1820 : Reproduction of recorded media",
        128: "1910 : Manufacture of coke oven products",
        129: "1920 : Manufacture of refined petroleum products",
        130: "2011 : Manufacture of industrial gases",
        131: "2012 : Manufacture of dyes and pigments",
        132: "2013 : Manufacture of other inorganic basic chemicals",
        133: "2014 : Manufacture of other organic basic chemicals",
        134: "2015 : Manufacture of fertilisers and nitrogen compounds",
        135: "2016 : Manufacture of plastics in primary forms",
        136: "2017 : Manufacture of synthetic rubber in primary forms",
        137: "2020 : Manufacture of pesticides and other agrochemical products",
        138: "2030 : Manufacture of paints, varnishes and similar coatings, printing ink and mastics",
        139: "2041 : Manufacture of soap and detergents, cleaning and polishing preparations",
        140: "2042 : Manufacture of perfumes and toilet preparations",
        141: "2051 : Manufacture of explosives",
        142: "2052 : Manufacture of glues",
        143: "2053 : Manufacture of essential oils",
        144: "2059 : Manufacture of other chemical products n.e.c.",
        145: "2060 : Manufacture of man-made fibres",
        146: "2110 : Manufacture of basic pharmaceutical products",
        147: "2120 : Manufacture of pharmaceutical preparations",
        148: "2211 : Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres",
        149: "2219 : Manufacture of other rubber products",
        150: "2221 : Manufacture of plastic plates, sheets, tubes and profiles",
        151: "2222 : Manufacture of plastic packing goods",
        152: "2223 : Manufacture of buildersÆ ware of plastic",
        153: "2229 : Manufacture of other plastic products",
        154: "2311 : Manufacture of flat glass",
        155: "2312 : Shaping and processing of flat glass",
        156: "2313 : Manufacture of hollow glass",
        157: "2314 : Manufacture of glass fibres",
        158: "2319 : Manufacture and processing of other glass, including technical glassware",
        159: "2320 : Manufacture of refractory products",
        160: "2331 : Manufacture of ceramic tiles and flags",
        161: "2332 : Manufacture of bricks, tiles and construction products, in baked clay",
        162: "2341 : Manufacture of ceramic household and ornamental articles",
        163: "2342 : Manufacture of ceramic sanitary fixtures",
        164: "2343 : Manufacture of ceramic insulators and insulating fittings",
        165: "2344 : Manufacture of other technical ceramic products",
        166: "2349 : Manufacture of other ceramic products",
        167: "2351 : Manufacture of cement",
        168: "2352 : Manufacture of lime and plaster",
        169: "2361 : Manufacture of concrete products for construction purposes",
        170: "2362 : Manufacture of plaster products for construction purposes",
        171: "2363 : Manufacture of ready-mixed concrete",
        172: "2364 : Manufacture of mortars",
        173: "2365 : Manufacture of fibre cement",
        174: "2369 : Manufacture of other articles of concrete, plaster and cement",
        175: "2370 : Cutting, shaping and finishing of stone",
        176: "2391 : Production of abrasive products",
        177: "2399 : Manufacture of other non-metallic mineral products n.e.c.",
        178: "2410 : Manufacture of basic iron and steel and of ferro-alloys",
        179: "2420 : Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",
        180: "2431 : Cold drawing of bars",
        181: "2432 : Cold rolling of narrow strip",
        182: "2433 : Cold forming or folding",
        183: "2434 : Cold drawing of wire",
        184: "2441 : Precious metals production",
        185: "2442 : Aluminium production",
        186: "2443 : Lead, zinc and tin production",
        187: "2444 : Copper production",
        188: "2445 : Other non-ferrous metal production",
        189: "2446 : Processing of nuclear fuel",
        190: "2451 : Casting of iron",
        191: "2452 : Casting of steel",
        192: "2453 : Casting of light metals",
        193: "2454 : Casting of other non-ferrous metals",
        194: "2511 : Manufacture of metal structures and parts of structures",
        195: "2512 : Manufacture of doors and windows of metal",
        196: "2521 : Manufacture of central heating radiators and boilers",
        197: "2529 : Manufacture of other tanks, reservoirs and containers of metal",
        198: "2530 : Manufacture of steam generators, except central heating hot water boilers",
        199: "2540 : Manufacture of weapons and ammunition",
        200: "2550 : Forging, pressing, stamping and roll-forming of metal; powder metallurgy",
        201: "2561 : Treatment and coating of metals",
        202: "2562 : Machining",
        203: "2571 : Manufacture of cutlery",
        204: "2572 : Manufacture of locks and hinges",
        205: "2573 : Manufacture of tools",
        206: "2591 : Manufacture of steel drums and similar containers",
        207: "2592 : Manufacture of light metal packaging",
        208: "2593 : Manufacture of wire products, chain and springs",
        209: "2594 : Manufacture of fasteners and screw machine products",
        210: "2599 : Manufacture of other fabricated metal products n.e.c.",
        211: "2611 : Manufacture of electronic components",
        212: "2612 : Manufacture of loaded electronic boards",
        213: "2620 : Manufacture of computers and peripheral equipment",
        214: "2630 : Manufacture of communication equipment",
        215: "2640 : Manufacture of consumer electronics",
        216: "2651 : Manufacture of instruments and appliances for measuring, testing and navigation",
        217: "2652 : Manufacture of watches and clocks",
        218: "2660 : Manufacture of irradiation, electromedical and electrotherapeutic equipment",
        219: "2670 : Manufacture of optical instruments and photographic equipment",
        220: "2680 : Manufacture of magnetic and optical media",
        221: "2711 : Manufacture of electric motors, generators and transformers",
        222: "2712 : Manufacture of electricity distribution and control apparatus",
        223: "2720 : Manufacture of batteries and accumulators",
        224: "2731 : Manufacture of fibre optic cables",
        225: "2732 : Manufacture of other electronic and electric wires and cables",
        226: "2733 : Manufacture of wiring devices",
        227: "2740 : Manufacture of electric lighting equipment",
        228: "2751 : Manufacture of electric domestic appliances",
        229: "2752 : Manufacture of non-electric domestic appliances",
        230: "2790 : Manufacture of other electrical equipment",
        231: "2811 : Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",
        232: "2812 : Manufacture of fluid power equipment",
        233: "2813 : Manufacture of other pumps and compressors",
        234: "2814 : Manufacture of other taps and valves",
        235: "2815 : Manufacture of bearings, gears, gearing and driving elements",
        236: "2821 : Manufacture of ovens, furnaces and furnace burners",
        237: "2822 : Manufacture of lifting and handling equipment",
        238: "2823 : Manufacture of office machinery and equipment (except computers and peripheral equipment)",
        239: "2824 : Manufacture of power-driven hand tools",
        240: "2825 : Manufacture of non-domestic cooling and ventilation equipment",
        241: "2829 : Manufacture of other general-purpose machinery n.e.c.",
        242: "2830 : Manufacture of agricultural and forestry machinery",
        243: "2841 : Manufacture of metal forming machinery",
        244: "2849 : Manufacture of other machine tools",
        245: "2891 : Manufacture of machinery for metallurgy",
        246: "2892 : Manufacture of machinery for mining, quarrying and construction",
        247: "2893 : Manufacture of machinery for food, beverage and tobacco processing",
        248: "2894 : Manufacture of machinery for textile, apparel and leather production",
        249: "2895 : Manufacture of machinery for paper and paperboard production",
        250: "2896 : Manufacture of plastics and rubber machinery",
        251: "2899 : Manufacture of other special-purpose machinery n.e.c.",
        252: "2910 : Manufacture of motor vehicles",
        253: "2920 : Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers",
        254: "2931 : Manufacture of electrical and electronic equipment for motor vehicles",
        255: "2932 : Manufacture of other parts and accessories for motor vehicles",
        256: "3011 : Building of ships and floating structures",
        257: "3012 : Building of pleasure and sporting boats",
        258: "3020 : Manufacture of railway locomotives and rolling stock",
        259: "3030 : Manufacture of air and spacecraft and related machinery",
        260: "3040 : Manufacture of military fighting vehicles",
        261: "3091 : Manufacture of motorcycles",
        262: "3092 : Manufacture of bicycles and invalid carriages",
        263: "3099 : Manufacture of other transport equipment n.e.c.",
        264: "3101 : Manufacture of office and shop furniture",
        265: "3102 : Manufacture of kitchen furniture",
        266: "3103 : Manufacture of mattresses",
        267: "3109 : Manufacture of other furniture",
        268: "3211 : Striking of coins",
        269: "3212 : Manufacture of jewellery and related articles",
        270: "3213 : Manufacture of imitation jewellery and related articles",
        271: "3220 : Manufacture of musical instruments",
        272: "3230 : Manufacture of sports goods",
        273: "3240 : Manufacture of games and toys",
        274: "3250 : Manufacture of medical and dental instruments and supplies",
        275: "3291 : Manufacture of brooms and brushes",
        276: "3299 : Other manufacturing n.e.c.",
        277: "3311 : Repair of fabricated metal products",
        278: "3312 : Repair of machinery",
        279: "3313 : Repair of electronic and optical equipment",
        280: "3314 : Repair of electrical equipment",
        281: "3315 : Repair and maintenance of ships and boats",
        282: "3316 : Repair and maintenance of aircraft and spacecraft",
        283: "3317 : Repair and maintenance of transport equipment n.e.c.",
        284: "3319 : Repair of other equipment",
        285: "3320 : Installation of industrial machinery and equipment",
        286: "3511 : Production of electricity",
        287: "3512 : Transmission of electricity",
        288: "3513 : Distribution of electricity",
        289: "3514 : Trade of electricity",
        290: "3521 : Manufacture of gas",
        291: "3522 : Distribution of gaseous fuels through mains",
        292: "3523 : Trade of gas through mains",
        293: "3530 : Steam and air conditioning supply",
        294: "3600 : Water collection, treatment and supply",
        295: "3700 : Sewerage",
        296: "3811 : Collection of non-hazardous waste",
        297: "3812 : Collection of hazardous waste",
        298: "3821 : Treatment and disposal of non-hazardous waste",
        299: "3822 : Treatment and disposal of hazardous waste",
        300: "3831 : Dismantling of wrecks",
        301: "3832 : Recovery of sorted materials",
        302: "3900 : Remediation activities and other waste management services",
        303: "4110 : Development of building projects",
        304: "4120 : Construction of residential and non-residential buildings",
        305: "4211 : Construction of roads and motorways",
        306: "4212 : Construction of railways and underground railways",
        307: "4213 : Construction of bridges and tunnels",
        308: "4221 : Construction of utility projects for fluids",
        309: "4222 : Construction of utility projects for electricity and telecommunications",
        310: "4291 : Construction of water projects",
        311: "4299 : Construction of other civil engineering projects n.e.c.",
        312: "4311 : Demolition",
        313: "4312 : Site preparation",
        314: "4313 : Test drilling and boring",
        315: "4321 : Electrical installation",
        316: "4322 : Plumbing, heat and air-conditioning installation",
        317: "4329 : Other construction installation",
        318: "4331 : Plastering",
        319: "4332 : Joinery installation",
        320: "4333 : Floor and wall covering",
        321: "4334 : Painting and glazing",
        322: "4339 : Other building completion and finishing",
        323: "4391 : Roofing activities",
        324: "4399 : Other specialised construction activities n.e.c.",
        325: "4511 : Sale of cars and light motor vehicles",
        326: "4519 : Sale of other motor vehicles",
        327: "4520 : Maintenance and repair of motor vehicles",
        328: "4531 : Wholesale trade of motor vehicle parts and accessories",
        329: "4532 : Retail trade of motor vehicle parts and accessories",
        330: "4540 : Sale, maintenance and repair of motorcycles and related parts and accessories",
        331: "4611 : Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods",
        332: "4612 : Agents involved in the sale of fuels, ores, metals and industrial chemicals",
        333: "4613 : Agents involved in the sale of timber and building materials",
        334: "4614 : Agents involved in the sale of machinery, industrial equipment, ships and aircraft",
        335: "4615 : Agents involved in the sale of furniture, household goods, hardware and ironmongery",
        336: "4616 : Agents involved in the sale of textiles, clothing, fur, footwear and leather goods",
        337: "4617 : Agents involved in the sale of food, beverages and tobacco",
        338: "4618 : Agents specialised in the sale of other particular products",
        339: "4619 : Agents involved in the sale of a variety of goods",
        340: "4621 : Wholesale of grain, unmanufactured tobacco, seeds and animal feeds",
        341: "4622 : Wholesale of flowers and plants",
        342: "4623 : Wholesale of live animals",
        343: "4624 : Wholesale of hides, skins and leather",
        344: "4631 : Wholesale of fruit and vegetables",
        345: "4632 : Wholesale of meat and meat products",
        346: "4633 : Wholesale of dairy products, eggs and edible oils and fats",
        347: "4634 : Wholesale of beverages",
        348: "4635 : Wholesale of tobacco products",
        349: "4636 : Wholesale of sugar and chocolate and sugar confectionery",
        350: "4637 : Wholesale of coffee, tea, cocoa and spices",
        351: "4638 : Wholesale of other food, including fish, crustaceans and molluscs",
        352: "4639 : Non-specialised wholesale of food, beverages and tobacco",
        353: "4641 : Wholesale of textiles",
        354: "4642 : Wholesale of clothing and footwear",
        355: "4643 : Wholesale of electrical household appliances",
        356: "4644 : Wholesale of china and glassware and cleaning materials",
        357: "4645 : Wholesale of perfume and cosmetics",
        358: "4646 : Wholesale of pharmaceutical goods",
        359: "4647 : Wholesale of furniture, carpets and lighting equipment",
        360: "4648 : Wholesale of watches and jewellery",
        361: "4649 : Wholesale of other household goods",
        362: "4651 : Wholesale of computers, computer peripheral equipment and software",
        363: "4652 : Wholesale of electronic and telecommunications equipment and parts",
        364: "4661 : Wholesale of agricultural machinery, equipment and supplies",
        365: "4662 : Wholesale of machine tools",
        366: "4663 : Wholesale of mining, construction and civil engineering machinery",
        367: "4664 : Wholesale of machinery for the textile industry and of sewing and knitting machines",
        368: "4665 : Wholesale of office furniture",
        369: "4666 : Wholesale of other office machinery and equipment",
        370: "4669 : Wholesale of other machinery and equipment",
        371: "4671 : Wholesale of solid, liquid and gaseous fuels and related products",
        372: "4672 : Wholesale of metals and metal ores",
        373: "4673 : Wholesale of wood, construction materials and sanitary equipment",
        374: "4674 : Wholesale of hardware, plumbing and heating equipment and supplies",
        375: "4675 : Wholesale of chemical products",
        376: "4676 : Wholesale of other intermediate products",
        377: "4677 : Wholesale of waste and scrap",
        378: "4690 : Non-specialised wholesale trade",
        379: "4711 : Retail sale in non-specialised stores with food, beverages or tobacco predominating",
        380: "4719 : Other retail sale in non-specialised stores",
        381: "4721 : Retail sale of fruit and vegetables in specialised stores",
        382: "4722 : Retail sale of meat and meat products in specialised stores",
        383: "4723 : Retail sale of fish, crustaceans and molluscs in specialised stores",
        384: "4724 : Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores",
        385: "4725 : Retail sale of beverages in specialised stores",
        386: "4726 : Retail sale of tobacco products in specialised stores",
        387: "4729 : Other retail sale of food in specialised stores",
        388: "4730 : Retail sale of automotive fuel in specialised stores",
        389: "4741 : Retail sale of computers, peripheral units and software in specialised stores",
        390: "4742 : Retail sale of telecommunications equipment in specialised stores",
        391: "4743 : Retail sale of audio and video equipment in specialised stores",
        392: "4751 : Retail sale of textiles in specialised stores",
        393: "4752 : Retail sale of hardware, paints and glass in specialised stores",
        394: "4753 : Retail sale of carpets, rugs, wall and floor coverings in specialised stores",
        395: "4754 : Retail sale of electrical household appliances in specialised stores",
        396: "4759 : Retail sale of furniture, lighting equipment and other household articles in specialised stores",
        397: "4761 : Retail sale of books in specialised stores",
        398: "4762 : Retail sale of newspapers and stationery in specialised stores",
        399: "4763 : Retail sale of music and video recordings in specialised stores",
        400: "4764 : Retail sale of sporting equipment in specialised stores",
        401: "4765 : Retail sale of games and toys in specialised stores",
        402: "4771 : Retail sale of clothing in specialised stores",
        403: "4772 : Retail sale of footwear and leather goods in specialised stores",
        404: "4773 : Dispensing chemist in specialised stores",
        405: "4774 : Retail sale of medical and orthopaedic goods in specialised stores",
        406: "4775 : Retail sale of cosmetic and toilet articles in specialised stores",
        407: "4776 : Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores",
        408: "4777 : Retail sale of watches and jewellery in specialised stores",
        409: "4778 : Other retail sale of new goods in specialised stores",
        410: "4779 : Retail sale of second-hand goods in stores",
        411: "4781 : Retail sale via stalls and markets of food, beverages and tobacco products",
        412: "4782 : Retail sale via stalls and markets of textiles, clothing and footwear",
        413: "4789 : Retail sale via stalls and markets of other goods",
        414: "4791 : Retail sale via mail order houses or via Internet",
        415: "4799 : Other retail sale not in stores, stalls or markets",
        416: "4910 : Passenger rail transport, interurban",
        417: "4920 : Freight rail transport",
        418: "4931 : Urban and suburban passenger land transport",
        419: "4932 : Taxi operation",
        420: "4939 : Other passenger land transport n.e.c.",
        421: "4941 : Freight transport by road",
        422: "4942 : Removal services",
        423: "4950 : Transport via pipeline",
        424: "5010 : Sea and coastal passenger water transport",
        425: "5020 : Sea and coastal freight water transport",
        426: "5030 : Inland passenger water transport",
        427: "5040 : Inland freight water transport",
        428: "5110 : Passenger air transport",
        429: "5121 : Freight air transport",
        430: "5122 : Space transport",
        431: "5210 : Warehousing and storage",
        432: "5221 : Service activities incidental to land transportation",
        433: "5222 : Service activities incidental to water transportation",
        434: "5223 : Service activities incidental to air transportation",
        435: "5224 : Cargo handling",
        436: "5229 : Other transportation support activities",
        437: "5310 : Postal activities under universal service obligation",
        438: "5320 : Other postal and courier activities",
        439: "5510 : Hotels and similar accommodation",
        440: "5520 : Holiday and other short stay accommodation",
        441: "5530 : Camping grounds, recreational vehicle parks and trailer parks",
        442: "5590 : Other accommodation",
        443: "5610 : Restaurants and mobile food service activities",
        444: "5621 : Event catering activities",
        445: "5629 : Other food service activities",
        446: "5630 : Beverage serving activities",
        447: "5811 : Book publishing",
        448: "5812 : Publishing of directories and mailing lists",
        449: "5813 : Publishing of newspapers",
        450: "5814 : Publishing of journals and periodicals",
        451: "5819 : Other publishing activities",
        452: "5821 : Publishing of computer games",
        453: "5829 : Other software publishing",
        454: "5911 : Motion picture, video and television programme production activities",
        455: "5912 : Motion picture, video and television programme post-production activities",
        456: "5913 : Motion picture, video and television programme distribution activities",
        457: "5914 : Motion picture projection activities",
        458: "5920 : Sound recording and music publishing activities",
        459: "6010 : Radio broadcasting",
        460: "6020 : Television programming and broadcasting activities",
        461: "6110 : Wired telecommunications activities",
        462: "6120 : Wireless telecommunications activities",
        463: "6130 : Satellite telecommunications activities",
        464: "6190 : Other telecommunications activities",
        465: "6201 : Computer programming activities",
        466: "6202 : Computer consultancy activities",
        467: "6203 : Computer facilities management activities",
        468: "6209 : Other information technology and computer service activities",
        469: "6311 : Data processing, hosting and related activities",
        470: "6312 : Web portals",
        471: "6391 : News agency activities",
        472: "6399 : Other information service activities n.e.c.",
        473: "6411 : Central banking",
        474: "6419 : Other monetary intermediation",
        475: "6420 : Activities of holding companies",
        476: "6430 : Trusts, funds and similar financial entities",
        477: "6491 : Financial leasing",
        478: "6492 : Other credit granting",
        479: "6499 : Other financial service activities, except insurance and pension funding, n.e.c.",
        480: "6511 : Life insurance",
        481: "6512 : Non-life insurance",
        482: "6520 : Reinsurance",
        483: "6530 : Pension funding",
        484: "6611 : Administration of financial markets",
        485: "6612 : Security and commodity contracts brokerage",
        486: "6619 : Other activities auxiliary to financial services, except insurance and pension funding",
        487: "6621 : Risk and damage evaluation",
        488: "6622 : Activities of insurance agents and brokers",
        489: "6629 : Other activities auxiliary to insurance and pension funding",
        490: "6630 : Fund management activities",
        491: "6810 : Buying and selling of own real estate",
        492: "6820 : Renting and operating of own or leased real estate",
        493: "6831 : Real estate agencies",
        494: "6832 : Management of real estate on a fee or contract basis",
        495: "6910 : Legal activities",
        496: "6920 : Accounting, bookkeeping and auditing activities; tax consultancy",
        497: "7010 : Activities of head offices",
        498: "7021 : Public relations and communication activities",
        499: "7022 : Business and other management consultancy activities",
        500: "7111 : Architectural activities",
        501: "7112 : Engineering activities and related technical consultancy",
        502: "7120 : Technical testing and analysis",
        503: "7211 : Research and experimental development on biotechnology",
        504: "7219 : Other research and experimental development on natural sciences and engineering",
        505: "7220 : Research and experimental development on social sciences and humanities",
        506: "7311 : Advertising agencies",
        507: "7312 : Media representation",
        508: "7320 : Market research and public opinion polling",
        509: "7410 : Specialised design activities",
        510: "7420 : Photographic activities",
        511: "7430 : Translation and interpretation activities",
        512: "7490 : Other professional, scientific and technical activities n.e.c.",
        513: "7500 : Veterinary activities",
        514: "7711 : Renting and leasing of cars and light motor vehicles",
        515: "7712 : Renting and leasing of trucks",
        516: "7721 : Renting and leasing of recreational and sports goods",
        517: "7722 : Renting of video tapes and disks",
        518: "7729 : Renting and leasing of other personal and household goods",
        519: "7731 : Renting and leasing of agricultural machinery and equipment",
        520: "7732 : Renting and leasing of construction and civil engineering machinery and equipment",
        521: "7733 : Renting and leasing of office machinery and equipment (including computers)",
        522: "7734 : Renting and leasing of water transport equipment",
        523: "7735 : Renting and leasing of air transport equipment",
        524: "7739 : Renting and leasing of other machinery, equipment and tangible goods n.e.c.",
        525: "7740 : Leasing of intellectual property and similar products, except copyrighted works",
        526: "7810 : Activities of employment placement agencies",
        527: "7820 : Temporary employment agency activities",
        528: "7830 : Other human resources provision",
        529: "7911 : Travel agency activities",
        530: "7912 : Tour operator activities",
        531: "7990 : Other reservation service and related activities",
        532: "8010 : Private security activities",
        533: "8020 : Security systems service activities",
        534: "8030 : Investigation activities",
        535: "8110 : Combined facilities support activities",
        536: "8121 : General cleaning of buildings",
        537: "8122 : Other building and industrial cleaning activities",
        538: "8129 : Other cleaning activities",
        539: "8130 : Landscape service activities",
        540: "8211 : Combined office administrative service activities",
        541: "8219 : Photocopying, document preparation and other specialised office support activities",
        542: "8220 : Activities of call centres",
        543: "8230 : Convention and trade show organizers",
        544: "8291 : Activities of collection agencies and credit bureaus",
        545: "8292 : Packaging activities",
        546: "8299 : Other business support service activities n.e.c.",
        547: "8411 : General public administration activities",
        548: "8412 : Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security",
        549: "8413 : Regulation of and contribution to more efficient operation of businesses",
        550: "8421 : Foreign affairs",
        551: "8422 : Defence activities",
        552: "8423 : Justice and judicial activities",
        553: "8424 : Public order and safety activities",
        554: "8425 : Fire service activities",
        555: "8430 : Compulsory social security activities",
        556: "8510 : Pre-primary education",
        557: "8520 : Primary education",
        558: "8531 : General secondary education",
        559: "8532 : Technical and vocational secondary education",
        560: "8541 : Post-secondary non-tertiary education",
        561: "8542 : Tertiary education",
        562: "8551 : Sports and recreation education",
        563: "8552 : Cultural education",
        564: "8553 : Driving school activities",
        565: "8559 : Other education n.e.c.",
        566: "8560 : Educational support activities",
        567: "8610 : Hospital activities",
        568: "8621 : General medical practice activities",
        569: "8622 : Specialist medical practice activities",
        570: "8623 : Dental practice activities",
        571: "8690 : Other human health activities",
        572: "8710 : Residential nursing care activities",
        573: "8720 : Residential care activities for learning disabilities, mental health and substance abuse",
        574: "8730 : Residential care activities for the elderly and disabled",
        575: "8790 : Other residential care activities",
        576: "8810 : Social work activities without accommodation for the elderly and disabled",
        577: "8891 : Child day-care activities",
        578: "8899 : Other social work activities without accommodation n.e.c.",
        579: "9001 : Performing arts",
        580: "9002 : Support activities to performing arts",
        581: "9003 : Artistic creation",
        582: "9004 : Operation of arts facilities",
        583: "9101 : Library and archive activities",
        584: "9102 : Museum activities",
        585: "9103 : Operation of historical sites and buildings and similar visitor attractions",
        586: "9104 : Botanical and zoological gardens and nature reserve activities",
        587: "9200 : Gambling and betting activities",
        588: "9311 : Operation of sports facilities",
        589: "9312 : Activities of sport clubs",
        590: "9313 : Fitness facilities",
        591: "9319 : Other sports activities",
        592: "9321 : Activities of amusement parks and theme parks",
        593: "9329 : Other amusement and recreation activities",
        594: "9411 : Activities of business and employers membership organisations",
        595: "9412 : Activities of professional membership organisations",
        596: "9420 : Activities of trade unions",
        597: "9491 : Activities of religious organisations",
        598: "9492 : Activities of political organisations",
        599: "9499 : Activities of other membership organisations n.e.c.",
        600: "9511 : Repair of computers and peripheral equipment",
        601: "9512 : Repair of communication equipment",
        602: "9521 : Repair of consumer electronics",
        603: "9522 : Repair of household appliances and home and garden equipment",
        604: "9523 : Repair of footwear and leather goods",
        605: "9524 : Repair of furniture and home furnishings",
        606: "9525 : Repair of watches, clocks and jewellery",
        607: "9529 : Repair of other personal and household goods",
        608: "9601 : Washing and (dry-)cleaning of textile and fur products",
        609: "9602 : Hairdressing and other beauty treatment",
        610: "9603 : Funeral and related activities",
        611: "9604 : Physical well-being activities",
        612: "9609 : Other personal service activities n.e.c.",
        613: "9700 : Activities of households as employers of domestic personnel",
        614: "9810 : Undifferentiated goods-producing activities of private households for own use",
        615: "9820 : Undifferentiated service-producing activities of private households for own use",
        616: "9900 : Activities of extraterritorial organisations and bodies",

    }
}

_CUSTOM_EXCLUSIONS = {
    'hc': {
        'age': [{'own_val': 1, 'other_vals': {1, 2, 3}}],
        'agg_age': [{'own_val': 1, 'other_vals': {1}}]
    },
    # TODO check if children are students or non-working age in pop_emp
    'pop_emp': {
        'age': [{'own_val': i, 'other_vals': {1, 2, 3}} for i in range(1, 4)]
    }
}

CUSTOM_SEGMENTS = dict()
for key, values in _CUSTOM_SEGMENT_CATEGORIES.items():
    exclusions = []
    # check for exclusions
    if key in _CUSTOM_EXCLUSIONS.keys():
        for other_category, exclusion_definitions in _CUSTOM_EXCLUSIONS[key].items():
            for definition in exclusion_definitions:
                exclusions.append(Exclusion(seg_name=other_category, **definition))

    CUSTOM_SEGMENTS[key] = Segment(name=key, values=values, exclusions=exclusions)

if __name__ == '__main__':
    example = ['p', 'tp', 'TfN', 'm', 'Land-Use', 'g']

    print(split_input_segments(example))
